config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :statements, only: %i[index show]
  resources :policies, only: [:index]
  resources :articles
  resources :tags, only: %i[new create edit]
  resources :article_tags, except: %i[show index]
  resources :posts
  resources :post_tags, except: %i[show index]
  resources :messages, only: %i[new create]

  root 'statements#index'
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  mount_uploader :picture, ArticlePhotoUploader

  has_many :article_tags
  has_many :tags, through: :article_tags

  validates :title, presence: true
  validates :author, presence: true
  validates :body, presence: true
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  def index
    @articles = Article.all.order('created_at DESC')
    @tags = Tag.all
    @article_tags = ArticleTag.all
  end

  def show
    @article = Article.find(params[:id])
    @tags = Tag.all
    @article_tags = ArticleTag.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = 'New Article Added!'
      redirect_to new_article_tag_path
    else
      flash[:alert] = 'New Article Not Created'
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
    @article_tag = ArticleTag.all
  end

  def update
    @article = Article.find(params[:id])
    if @article.update_attributes(article_params)
      flash[:notice] = 'Article Updated!'
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])

    if @article.destroy
      flash[:notice] = 'Article has been deleted.'
      redirect_to new_article_path
    end
  end

  private

  def article_params
    params.require(:article).permit(
      :title,
      :author,
      :body,
      :picture,
      :url
    )
  end
end

app/views/articles/edit.html.erb
<% if current_user.admin? %>
<%= link_to 'Back to Article', article_path(@article.id) %>
  <div class='page'>
    <% if @article.errors.any? %>
      <div>
        <h2><%= pluralize(@article.errors.count, "error") %> prohibited this info from being saved:</h2>
        <ul>
          <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <h1 class="form_header">Update Article</h1>
    <%= form_for @article do |a| %>
      <div class="row">
        <%= a.label :picture, 'Picture', class: 'form-actions' %>
        <%= a.file_field :picture, class: 'text_field' %>
      </div>
      <div class="row">
        <%= a.label :title, 'Title', class: 'form-actions' %>
        <%= a.text_field :title, class: 'text_field' %>
      </div>
      <div class="row">
        <%= a.label :author, 'Author', class: 'form-actions' %>
        <%= a.text_field :author, class: 'text_field' %>
      </div>
      <div class="row">
        <%= a.label :url, 'URL', class: 'form-actions' %>
        <%= a.text_field :url, class: 'text_field' %>
      </div>
      <div class="row">
        <%= a.label :body, 'Body', class: 'form-actions' %>
        <%= a.text_area :body, class: 'text_area' %>
      </div><div>
        <h3>Click on the tag you want to remove:</h3>
        <% @article_tag.each do |at| %>
          <% if at.article_id == @article.id %>
            <p><%= link_to at.tag.tag, article_tags_path(at.id), data: { confirm: 'Are you sure you want to remove this tag: %{word}' % { word: at.tag.tag} }, method: :delete, :class => 'user_links' %> <br />
          <% end %>
        <% end %>
        <%= link_to 'Add New Tag', new_article_tag_path %>
      </div>
      <div class="form-actions">
        <%= a.button 'Submit' %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/articles/index.html.erb
<br>
  <h1 class="title is-1 is-family-secondary has-text-centered">Articles</h1>
<br>
<div class="container">
  <% @articles.each do |a| %>
    <div class="card">
      <header class="card-header">
        <p class="card-header-title is-centered">
          <%= a.title %>
        </p>
      </header>
      <div class="card-content">
        <div class="media">
           <div class="media-left">
             <figure class="image is-128x128">
               <img <%= image_tag (a.picture.url) %>
             </figure>
           </div>
           <div class="media-content">
             <p class="content is-medium"><%= truncate(a.body, length: 100, escape: false) %></p>
           </div>
         </div>
        <div class="content">
          <br>
          <time><%= a.created_at.strftime("%B %d, %Y") %></time>
        </div>
      </div>
      <footer class="card-footer">
        <%= link_to "Read", article_path(a.id), :class=>"card-footer-item" %>
      </footer>
    </div>
    <br>
  <% end %>
</div>

app/views/articles/new.html.erb
<% if current_user.admin? %>
  <div class='page'>
    <h1 class="form_header">Add a new Article</h1>
    <%= form_for @article do |a| %>
      <div class="row">
        <%= a.label :picture, 'Picture', class: 'form-actions' %>
        <%= a.file_field :picture, class: 'text_field' %>
      </div>
      <div class="row">
        <%= a.label :title, 'Title', class: 'form-actions' %>
        <%= a.text_field :title, class: 'text_field' %>
      </div>
      <div class="row">
        <%= a.label :author, 'Author', class: 'form-actions' %>
        <%= a.text_field :author, class: 'text_field' %>
      </div><div class="row">
        <%= a.label :url, 'URL', class: 'form-actions' %>
        <%= a.text_field :url, class: 'text_field' %>
      </div>
      <div class="row">
        <%= a.label :body, 'Body', class: 'form-actions' %>
        <%= a.text_area :body, class: 'text_area' %>
      </div>
      <div class="form-actions">
        <%= a.button 'Submit' %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/articles/show.html.erb
<div class="container">
  <br>
  <section class="has-text-centered">
    <button class="button has-background-white"><%= link_to 'Back to Article Index', articles_path %> </button>
  </section>
  <br>
  <section class="section has-background-warning">
    <div class="columns">
      <div class="column">
        <figure class="image is-5x4">
          <%= image_tag (@article.picture.url) %>
        </figure>
      </div>
      <div class="column">
        <br><br><br><br>
        <h2 class="title has-text-white has-text-centered is-family-secondary is-size-1"><%= @article.title %></h2>
        <br>
        <h2 class="subtitle has-text-white">By: <%= @article.created_at.strftime("%B %d, %Y") %></h2>
        <h2 class="subtitle has-text-white">By: <%= @article.author %></h2>
        <% if @article.url != '' %>
          <h2 class="subtitle has-text-white">Find this article at: <%= link_to @article.url %></h2>
        <% end %>
        <br>
      </div>
    </div>
  </section>
  <section>
    <br>
    <p><%= simple_format @article.body %></p>
    <div>
      <% @article_tags.each do |at| %>
        <% if at.article_id == @article.id %>
          <%= at.tag.tag %>
        <% end %>
      <% end %>
    </div>
  </section>
</div>
    <% if user_signed_in? %>
      <% if current_user.admin? %>
        <%= link_to edit_article_path do  %>
          <i class="far fa-edit fa-2x"></i>
        <% end %>
        <%= link_to article_path, data: { confirm: "Are you sure?" }, method: :delete do %>
          <i class="far fa-trash-alt fa-2x"></i>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>