config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :statements, only: %i[index show]
  resources :policies, only: [:index]
  resources :articles
  resources :tags, only: %i[new create edit]
  resources :article_tags, except: %i[show index]
  resources :posts
  resources :post_tags, except: %i[show index]
  resources :messages, only: %i[new create]

  root 'statements#index'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, presence: true, uniqueness: true
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, on: :create
  validates :name, presence: true

  def admin?
    role == 'admin'
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = 'Account was successfully created'
      redirect_to current_user_path
    else
      render :new
    end
  end

  def destroy
    @user = User.find(params[:id])

    if @user.destroy
      flash[:notice] = 'User has been deleted.'
      redirect_to new_user_path
    end
  end
end

app/views/users/show.html.erb
<% if current_user.admin? %>
  <div class="options">
    <ul>
      <li> <%= link_to "New Article", new_article_path %></li>
      <li> <%= link_to "New Post", new_post_path %></li>
      <li> <%= link_to "New Message", new_message_path %></li>
      <li><%= link_to "Articles", articles_path %></li>
      <li><%= link_to "Blog", posts_path %></li>
    </ul>
  </div>
<% else %>
  <h3>There is no user specific content, please return to the main pages</h3>
  <%= link_to "Back", statements_path %>
<% end %>