config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :statements, only: %i[index show]
  resources :policies, only: [:index]
  resources :articles
  resources :tags, only: %i[new create edit]
  resources :article_tags, except: %i[show index]
  resources :posts
  resources :post_tags, except: %i[show index]
  resources :messages, only: %i[new create]

  root 'statements#index'
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  mount_uploader :picture, PostsPhotoUploader
  has_many :post_tags
  has_many :tags, through: :post_tags

  validates :title, presence: true
  validates :author, presence: true
  validates :catagory, presence: true
  validates :body, presence: true
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  def index
    @posts = Post.all.order('created_at DESC')
    @post_tags = PostTag.all
  end

  def show
    @post = Post.find(params[:id])
    @post_tags = PostTag.all
  end

  def new
    @post = Post.new
    @post_tags = PostTag.all
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = 'New Post Added!'
      redirect_to new_post_path
    else
      flash[:alert] = 'New Post Not Created'
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    @post_tags = PostTag.all
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      flash[:notice] = 'Post Updated!'
      redirect_to posts_path
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])

    if @post.destroy
      flash[:notice] = 'Post has been deleted.'
      redirect_to edit_post_path(@post.post_id)
    end
  end

  private

  def post_params
    params.require(:post).permit(
      :title,
      :author,
      :catagory,
      :body,
      :picture
    )
  end
end

app/views/posts/edit.html.erb
<% if current_user.admin? %>
<%= link_to 'Back to Post', post_path(@post.id) %>
  <div class='page'>
    <% if @post.errors.any? %>
      <div>
        <h2><%= pluralize(@post.errors.count, "error") %> prohibited this info from being saved:</h2>
        <ul>
          <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <h1 class="form_header">Update post</h1>
    <h2>For pictures, use catagory 'Picture'. For Videos, use catagory 'Video' </h2>
    <%= form_for @post do |p| %>
      <div class="row">
        <%= p.label :title, 'Title', class: 'form-actions' %>
        <%= p.text_field :title, class: 'text_field' %>
      </div>
      <div class="row">
        <%= p.label :author, 'Author', class: 'form-actions' %>
        <%= p.text_field :author, class: 'text_field' %>
        <h2>DOUBLE CHECK CATEGORY IS CORRECT!!!!</h2>
        <%= p.label :catagory, 'Catagory', class: 'form-actions' %>
        <%= p.select :catagory, options_for_select([['Normal', 'normal'], ['Guest', 'guest'], ['Other', 'other'], ['Picture', 'picture']]) %>
      </div>
      <h3>Only upload picture if picture catagory is selected</h3>
      <div class="row">
        <%= p.label :picture, 'Picture', class: 'form-actions' %>
        <%= p.file_field :picture, class: 'text_field' %>
      </div>
      <h2>If you are posting a video, enter the embeded url in the body</h2>
      <div class="row">
        <%= p.label :body, 'Body', class: 'form-actions' %>
        <%= p.text_area :body, class: 'text_area' %>
      </div>
      <div>
        <h3>Click on the Tag you want to remove:</h3>
        <% @post_tags.each do |pt| %>
          <% if pt.post_id == @post.id %>
            <p><%= link_to pt.tag.tag, post_tags_path(pt.id), data: { confirm: 'Are you sure you want to remove this tag: %{word}' % { word: pt.tag.tag} }, method: :delete, :class => 'user_links' %> <br />
          <% end %>
        <% end %>
        <%= link_to 'Add New Tag', new_post_tag_path %>
      </div>
      <div class="form-actions">
        <%= p.button 'Submit' %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/posts/index.html.erb
<div class="container"><br>
  <h1 class="title is-1 is-family-secondary has-text-centered">Our Blog</h1>
  <br>
  <% @posts.each do |p| %>
    <div class="card">
      <div class="card-content">
        <% if p.catagory == 'picture' %>
          <img class="blog_picture" <%= image_tag (p.picture.url) %>
        <% elsif p.catagory == 'other' %>
          <figure class="centered">
            <iframe class="has-ratio" width="560" height="315" src=<%= p.body %> frameborder="0" allowfullscreen></iframe>
          </figure>
        <% else %>
          <p class="title"><%= truncate(p.body, length: 100, escape: false) %></p>
        <% end %>
        <% case p.catagory %>
          <% when 'guest' %>
            <p class="subtitle has-text-success"> Guest Contributor <%= p.author %> </p>
          <% when 'normal' %>
            <p class="subtitle has-text-warning">By <%= p.author %> </p>
          <% else %>
            <p class="subtitle has-text-danger">By <%= p.author %> </p>
          <% end %>
      </div>
      <footer class="card-footer">
        <p class="card-footer-item">
          <span>
            <%= link_to 'Read', post_path(p.id) %>
          </span>
        </p>
        <p class="card-footer-item">
          <span>
            <%= p.created_at.strftime("%B %d, %Y") %>
          </span>
        </p>
      </footer>
    </div>
    <br>
  <% end %>
</div>

app/views/posts/new.html.erb
<% if current_user.admin? %>
  <div class='page'>
    <% if @post.errors.any? %>
      <div>
        <h2><%= pluralize(@post.errors.count, "error") %> prohibited this info from being saved:</h2>
        <ul>
          <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <h1 class="form_header">New Post</h1>
    <h2>For pictures, use catagory 'Picture'. For Videos, use catagory 'Video' </h2>
    <%= form_for @post do |p| %>
      <div class="row">
        <%= p.label :title, 'Title', class: 'form-actions' %>
        <%= p.text_field :title, class: 'text_field' %>
      </div>
      <div class="row">
        <%= p.label :author, 'Author', class: 'form-actions' %>
        <%= p.text_field :author, class: 'text_field' %>
        <%= p.label :catagory, 'Catagory', class: 'form-actions' %>
        <%= p.select :catagory, options_for_select([['Normal', 'normal'], ['Guest', 'guest'], ['Video', 'other'], ['Picture', 'picture']]) %>
      </div>
      <h3>Only upload picture if picture catagory is selected</h3>
      <div class="row">
        <%= p.label :picture, 'Picture', class: 'form-actions' %>
        <%= p.file_field :picture, class: 'text_field' %>
      </div>
      <h2>If you are posting a video, enter the embeded url in the body</h2>
      <div class="row">
        <%= p.label :body, 'Body', class: 'form-actions' %>
        <%= p.text_area :body, class: 'text_area' %>
      </div>
      <div>
        <%= link_to 'Add New Tag', new_post_tag_path %>
      </div>
      <div class="form-actions">
        <%= p.button 'Submit' %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/posts/show.html.erb
<div class="container">
  <br>
  <section class="has-text-centered">
    <button class="button has-background-white"><%= link_to 'Back to Blog Index', posts_path %> </button>
  </section>
  <br>
  <section class="has-text-centered">
    <h2 class="title is-family-secondary"><%= @post.title %></h2>
    <p><%= @post.created_at.strftime("%B %d, %Y") %></p>
    <% case @post.catagory %>
      <% when 'guest' %>
        <h3 class="guest"> Guest Contributor <%= @post.author %> </h3>
      <% when 'normal' %>
        <h3 class="us">By <%= @post.author %> </h3>
      <% else %>
        <h3 class="other">By <%= @post.author %> </h3>
    <% end %>
    <br>
  </section>
  <section>
    <% if @post.catagory == 'picture' %>
      <img class="blog_picture" <%= image_tag (@post.picture.url) %>
    <% elsif @post.catagory == 'other' %>
      <figure class="centered">
        <iframe class="has-ratio" width="560" height="315" src=<%= @post.body %> frameborder="0" allowfullscreen></iframe>
      </figure>
    <% else %>
      <p><%= simple_format @post.body %></p>
    <% end %>
  </section>
  <section>
    <div class="column">
      <h3>Tags:
      <% @post_tags.each do |pt| %>
        <% if pt.post_id == @post.id %>
          <%= pt.tag.tag %></h3>
        <% end %>
      <% end %>
    </div>
  </section>
  <% if user_signed_in? %>
    <% if current_user.admin? %>
      <%= link_to edit_post_path do  %>
        <i class="far fa-edit fa-2x"></i>
      <% end %>
      <%= link_to post_path, data: { confirm: "Are you sure?" }, method: :delete do %>
        <i class="far fa-trash-alt fa-2x"></i>
      <% end %>
    <% end %>
  <% end %>
</div>