config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :statements, only: %i[index show]
  resources :policies, only: [:index]
  resources :articles
  resources :tags, only: %i[new create edit]
  resources :article_tags, except: %i[show index]
  resources :posts
  resources :post_tags, except: %i[show index]
  resources :messages, only: %i[new create]

  root 'statements#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HaltTheSilence</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'custom', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <script src="https://kit.fontawesome.com/877c4451bf.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <header>
      <div class="nav_back">
      <nav class="navbar has-background-light" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
         <a class="navbar-item is-size-3 is-family-secondary" href="https://bulma.io">
            HaltTheSilence
         </a>
          <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>
        <div id="navbarBasicExample" class="navbar-menu">
          <div class="navbar-end">
            <%= link_to "Home", statements_path, :class=>"navbar-item" %>
            <%= link_to "About Us", statement_path(1), :class=>"navbar-item" %>
            <%= link_to "Get Involved", new_message_path, :class=>"navbar-item" %>
            <%= link_to "Articles", articles_path, :class=>"navbar-item" %>
            <%= link_to "Blog", posts_path, :class=>"navbar-item" %>
            <% if user_signed_in? %>
              <%= link_to "User Home", user_path(current_user), :class=>"navbar-item" %>
            <% end %>
            <div class="navbar-item has-dropdown is-hoverable">
              <a class="navbar-link">
                Social Media
              </a>
              <div class="navbar-dropdown">
                <a class="navbar-item" href="https://haltthesilence.tumblr.com/" target="_blank">
                  <i class="fab fa-tumblr"></i>
                </a>
                <a class="navbar-item" href="https://twitter.com/HaltTheSilence" target="_blank">
                  <i class="fab fa-twitter"></i>
                </a>
                <a class="navbar-item" href="https://vm.tiktok.com/ZMJCvxoXt/" target="_blank">
                  <i class="fab fa-tiktok"></i>
                </a>
                <a class="navbar-item" href="https://www.instagram.com/haltthesilence/" target="_blank">
                  <i class="fab fa-instagram"></i>
                </a>
                <a class="navbar-item" href="https://www.youtube.com/channel/UCXhihcdsLpu_JcqYLAQ9MUA" target="_blank">
                  <i class="fab fa-youtube"></i>
                </a>
              </div>
            </div>
          </div>
        </div>
      </nav>
      </div>
    </header>
    <%= yield %>
  </body>
</html>

<script type="text/javascript">
  document.addEventListener('DOMContentLoaded', () => {

  // Get all "navbar-burger" elements
  const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

  // Check if there are any navbar burgers
  if ($navbarBurgers.length > 0) {

    // Add a click event on each of them
    $navbarBurgers.forEach( el => {
      el.addEventListener('click', () => {

        // Get the target from the "data-target" attribute
        const target = el.dataset.target;
        const $target = document.getElementById(target);

        // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
        el.classList.toggle('is-active');
        $target.classList.toggle('is-active');

      });
    });
  }

});
</script>